-- AlterTable
ALTER TABLE "Genre" ADD COLUMN     "numberOfBooks" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Region" ADD COLUMN     "numberOfAuthors" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "numberOfBooks" INTEGER NOT NULL DEFAULT 0;
